{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "bjj-mongodb.fullname" . }}-pvc
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-mongodb.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- range .Values.mongodb.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size | quote }}
  {{- if .Values.mongodb.persistence.storageClassName }}
  storageClassName: {{ .Values.mongodb.persistence.storageClassName | quote }}
  {{- end }}
{{- end }}