{{- if and .Values.mongodb.enabled .Values.secrets.mongodbRootPassword.enabled (not .Values.azure.enabled) .Values.secrets.mongodbRootPassword.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.mongodbRootPassword.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-mongodb.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.mongodbRootPassword.key }}: {{ .Values.secrets.mongodbRootPassword.value | quote }}
{{- end }}