{{- if .Values.mongodb.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bjj-mongodb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-mongodb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: mongo
      protocol: TCP
      name: mongo
  selector:
    {{- include "bjj-mongodb.selectorLabels" . | nindent 4 }}
{{- end }}