version: 2
updates:

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: wednesday
    labels:
      - dependencies
      - ci
    commit-message:
      prefix: ci

  - package-ecosystem: docker
    directory: /bjj-eire-api/artifact
    schedule:
      interval: weekly
      day: thursday
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore

  - package-ecosystem: docker
    directory: /bjj-eire-web/artifact
    schedule:
      interval: weekly
      day: thursday
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore

  - package-ecosystem: docker
    directory: /bjj-eire-mongodb/artifact
    schedule:
      interval: weekly
      day: thursday
    labels:
      - dependencies
      - docker
    commit-message:
      prefix: chore
