version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/bjj-eire-api"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/bjj-eire-web"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/bjj-eire-mongodb"
    schedule:
      interval: "weekly"
