{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bjj-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.api.autoscaling.enabled }}
  replicas: {{ .Values.api.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bjj-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.api.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "bjj-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.api.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.azure.enabled }}
      imagePullSecrets:
        - name: {{ include "bjj-api.fullname" . }}-acr-secret
      {{- end }}
      serviceAccountName: {{ include "bjj-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.api.podSecurityContext | nindent 8 }}
      {{- with .Values.api.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.api.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: api
        securityContext:
          {{- toYaml .Values.api.securityContext | nindent 10 }}
        image: "{{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.api.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.api.service.port }}
          protocol: TCP
        {{- if .Values.api.service.httpsPort }}
        - name: https
          containerPort: {{ .Values.api.service.httpsPort }}
          protocol: TCP
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "bjj-api.fullname" . }}
        env:
        - name: ConnectionStrings__Mongodb
          value: {{ include "bjj-api.mongodb.connectionString" . | quote }}
        {{- if .Values.api.kestrelCert.enabled }}
        - name: ASPNETCORE_Kestrel__Certificates__Default__Password
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secrets.apiKestrelCertPassword.name }}
              key: {{ .Values.secrets.apiKestrelCertPassword.key }}
        - name: ASPNETCORE_Kestrel__Certificates__Default__Path
          value: "{{ .Values.api.kestrelCert.mountPath }}/aspnetapp.pfx"
        {{- end }}
        {{- if .Values.api.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.api.livenessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.api.readinessProbe }}
        readinessProbe:
          {{- toYaml .Values.api.readinessProbe | nindent 10 }}
        {{- end }}
        {{- if .Values.api.startupProbe }}
        startupProbe:
          {{- toYaml .Values.api.startupProbe | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.api.resources | nindent 10 }}
        volumeMounts:
        {{- if .Values.api.kestrelCert.enabled }}
        - name: kestrel-cert
          mountPath: {{ .Values.api.kestrelCert.mountPath }}
          readOnly: true
        {{- end }}
        {{- if .Values.azure.enabled }}
        - name: secrets-store-vol
          mountPath: /mnt/secrets-store
          readOnly: true
        {{- end }}
      volumes:
      {{- if .Values.api.kestrelCert.enabled }}
      - name: kestrel-cert
        secret:
          secretName: {{ .Values.api.kestrelCert.secretName }}
      {{- end }}
      {{- if .Values.azure.enabled }}
      - name: secrets-store-vol
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: {{ include "bjj-api.fullname" . }}-akv-secrets
      {{- end }}
{{- end }}