{{- if and .Values.api.enabled .Values.api.kestrelCert.enabled (not .Values.azure.enabled) .Values.secrets.apiKestrelCertPassword.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.api.kestrelCert.secretName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "bjj-api.labels" . | nindent 4 }}
type: Opaque
data:
  aspnetapp.pfx: {{ .Values.secrets.apiKestrelCertPassword.value | quote }}
{{- end }}